version: '3'

services:

  nginx:
    build: ./nginx
    container_name: "sria_nginx"
    depends_on:
      - web
    ports:
      - "80:80"

  db:
    image: postgres:latest
    container_name: "sria_db"
    environment:
      - POSTGRES_USER=sria
      - POSTGRES_PASSWORD=Admin.123
      - POSTGRES_DB=sria_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  web:
    build: .
    container_name: "sria_web"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - db
