# Generated by Django 2.2.5 on 2019-09-27 17:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('biografia', models.TextField(blank=True, max_length=250, null=True, verbose_name='Biografia')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('adicionado', models.DateField(auto_now_add=True, verbose_name='Adicionado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='doctores')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('biografia', models.TextField(blank=True, max_length=500, null=True, verbose_name='Biografia')),
                ('directivo', models.BooleanField(default=False, verbose_name='Es parte del Directorio')),
                ('expresidente', models.BooleanField(default=False, verbose_name='Es Expresidente')),
                ('miembro', models.BooleanField(default=False, verbose_name='Es Miembro')),
                ('anio', models.IntegerField(default=2019, verbose_name='Año')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web Personal')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('adicionado', models.DateField(auto_now_add=True, verbose_name='Adicionado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagen', models.ImageField(upload_to='eventos')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('resumen', models.TextField(blank=True, max_length=250, null=True, verbose_name='Resumen')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('adicionado', models.DateField(auto_now_add=True, verbose_name='Adicionado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagen', models.ImageField(upload_to='noticias')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha Publicación')),
                ('resumen', models.TextField(blank=True, max_length=250, null=True, verbose_name='Resumen')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('adicionado', models.DateField(auto_now_add=True, verbose_name='Adicionado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Autor')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
