# Generated by Django 2.2.5 on 2019-10-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-periodo_fin'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='anio',
        ),
        migrations.AddField(
            model_name='doctor',
            name='periodo_fin',
            field=models.IntegerField(default=2019, verbose_name='Fin de Periodo'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='periodo_inicio',
            field=models.IntegerField(default=2019, verbose_name='Inicio de Periodo'),
        ),
    ]
