# Generated by Django 2.2.5 on 2019-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20191001_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('adicionado', models.DateField(auto_now_add=True, verbose_name='Adicionado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
